backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "site"
    label: "Сайт"
    files:
      - file: "content.json"
        label: "Контент"
        name: "content"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }
          - { label: "Текст", name: "text", widget: "text" }