backend:
  name: git-gateway
  branch: main

collections:
  - name: "site"
    label: "Сайт"
    files:
      - file: "content.json"
        label: "Контент"
        name: "content"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }
          - { label: "Текст", name: "text", widget: "text" }
          - label: "Отзывы"
            name: "reviews"
            widget: "list"
            fields:
              - { label: "Имя", name: "name", widget: "string" }
              - { label: "Текст", name: "text", widget: "text" }ext", widget: "text" }